
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://shamansim.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: "/"

# Google tracking id to track your visitors

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Simon Besson-Girard"
title: "Bioinformaticus nipponensis"
description: "French bioinformatics student, intern at RIKEN in Yokohama"
keywords: "japan, lifestyle, photography, science"
favicon: "/img/cropped-Flag_of_Yokohama_Kanagawa.ico"

################
# Header layout #
################

black-favicon: "/img/cropped-Flag_of_Yokohama_Kanagawa.ico"

background-img: "../img/P1060979.JPG"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 3000
lines: # You can add HTML Tags in the Text
  - text: "French bioinformatics student"
  - text: "Intern at RIKEN-CLST in Yokohama"
  - text: "Visiting Japan"
  - text: "Sharing my dailylife..."

me-img: "/img/cropped-Flag_of_Yokohama_Kanagawa.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 50

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: False
reddit-share: False
google-plus-share: False
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: False

disqus-shortname: "shamansim"

syntax-highlight: True

excerpt_separator: <!--more-->

############
# Timeline #
############

events:
  - image: "/img/timeline/hamarikyu.JPG"
    date: "Dimanche 10 avril 2016"
    description: "Shimbashi et Hamarikyu gardens"
  - image: "/img/timeline/shinjukuGyoen.JPG"
    date: "Samedi 9 avril 2016"
    description: "Parc de Shinjuku Gyoen et la rivière à Nakameguro"
  - image: "/img/timeline/asakusa.JPG"
    date: "Mardi 5 avril 2016"
    description: "Parc de Ueno, parc de Sumida et temple d'Asakusa"
  - image: "/img/timeline/kanamara.JPG"
    date: "Dimanche 3 avril 2016"
    description: "Kanamara-matsuri"
  - image: "/img/timeline/imperial.JPG"
    date: "Samedi 2 avril 2016"
    description: "Palais impérial et sanctuaire Yasukuni"
  - image: "/img/timeline/odaiba.JPG"
    date: "Dimanche 27 mars 2016"
    description: "Sortie à Odaiba"
  - image: "/img/timeline/meiji.JPG"
    date: "Samedi 26 mars 2016"
    description: "Parc de Yoyogi, le sanctuaire Meiji et Harajuku"
  - image: "/img/timeline/taimatsu.JPG"
    date: "Vendredi 25 mars 2016"
    description: "Shinki-sai Taimatsu-matsuri"
  - image: "/img/timeline/5lacs.JPG"
    date: "Samedi 19 mars 2016 - Lundi 21 mars 2016"
    description: "Excursion dans la région des 5 lacs et le Fuji-san"
  - image: "/img/timeline/takao.JPG"
    date: "Dimanche 13 mars 2016"
    description: "Le Takao-san et le rituel du feu"
  - image: "/img/timeline/enoshima.JPG"
    date: "Samedi 12 mars 2016"
    description: "Excursion à Enoshima"
  - image: "/img/timeline/shinjuku.JPG"
    date: "Jeudi 10 mars 2016"
    description: "Sortie à Shinjuku"
  - image: "/img/timeline/shinjukuIngress.JPG"
    date: "Mardi 8 mars 2016"
    description: "Ingress à Shinjuku"
  - image: "/img/timeline/hinaMatsuri.JPG"
    date: "Dimanche 6 mars 2016"
    description: "Le musée du Hina-matsuri et le quartier de Meguro"
  - image: "/img/timeline/omotesando.JPG"
    date: "Samedi 5 mars 2016"
    description: "Sortie au parc Yoyogi et dans le quartier d'Omotesando"
  - image: "/img/timeline/marathon.JPG"
    date: "Dimanche 28 février 2016"
    description: "Le marathon de Tokyo"
  - image: "/img/timeline/sukiyaki.JPG"
    date: "Samedi 27 février 2016"
    description: "Sukiyaki party avec les colloques"
  - image: "/img/timeline/shibuya.JPG"
    date: "Vendredi 26 février 2016"
    description: "Avec les amis, à Shibuya"
  - image: "/img/timeline/akb.JPG"
    date: "Samedi 20 février 2016"
    description: "Sortie à Akihabara"
  - image: "/img/timeline/chinois.JPG"
    date: "Samedi 13 février 2016"
    description: "Visite du quartier chinois de Yokohama"
  - image: "/img/timeline/aPied.JPG"
    date: "Jeudi 11 février 2016"
    description: "À pied, entre Shinkoyasu et Yokohama"
  - image: "/img/timeline/nippori.JPG"
    date: "Dimanche 7 février 2016"
    description: "Sortie à Nippori"
  - image: "/img/timeline/sakuragichou.JPG"
    date: "Samedi 6 février 2016"
    description: "Sortie à Sakuragichou"
  - image: "/img/timeline/collegues.JPG"
    date: "Vendredi 5 février 2016"
    description: "Soirée avec les collègues"
  - image: "/img/timeline/yokohama.JPG"
    date: "Mardi 2 février 2016"
    description: "Première sortie à Yokohama"
  - image: "/img/timeline/premierJour.JPG"
    date: "Lundi 1 février 2016"
    description: "Premier jour de travail"
  - image: "/img/timeline/sharehouse.JPG"
    date: "Dimanche 31 janvier 2016"
    description: "Arrivée dans ma sharehouse"

# First image of the Timeline

timeline-img: "/img/timeline/planeScreen.JPG"

###########
# Contact #
###########

email: "bioinformaticusnipponensis@besson-girard.fr"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Simon Besson-Girard is a French bioinformatics student, currently in an internship at the RIKEN in the Yokohama Campus."
author_blurb_image: "/img/blurb.png"

##################
# Social Buttons #
##################

social:
  - title: "instagram"
    url: "https://www.instagram.com/shamansim/"
  - title: "twitter"
    url: "https://twitter.com/SimonBesson"
  - title: "github"
    url: "https://github.com/shamansim"
  - title: "rss"
    url: "https://shamansim.github.io/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
